# Generated by Django 2.0.2 on 2018-02-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0002_listalocutores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurso',
            name='ruta_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/media/'),
        ),
    ]
