# Generated by Django 2.0.2 on 2018-02-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0003_auto_20180224_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurso',
            name='imagen_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
