# Generated by Django 2.0.2 on 2018-02-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0004_concurso_imagen_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurso',
            name='imagen_file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
