# Generated by Django 2.0.2 on 2018-02-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0006_auto_20180224_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
