# Generated by Django 2.0.2 on 2018-02-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0007_auto_20180224_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concurso',
            name='imagen_file',
        ),
        migrations.AlterField(
            model_name='concurso',
            name='ruta_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/media/'),
        ),
    ]
