# Generated by Django 2.0.2 on 2018-02-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0010_audiolocutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiolocutor',
            name='archivo_convertido',
            field=models.FileField(default='Null', upload_to=''),
        ),
    ]
