# Generated by Django 2.0.2 on 2018-02-27 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebConcursos', '0011_auto_20180225_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresa', models.CharField(blank=True, default='Asignar Empresa', max_length=200)),
                ('Rol', models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Marketing', 'Marketing')], default='Administrador', max_length=200)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
